default_context:
  project_name: 'groupkash-fastapi'
  project_slug: 'groupkash-fastapi'
  domain_main: 'groupkash-fastapi.com'
  domain_staging: 'stag.groupkash-fastapi.com'
  domain_base_api_url: 'http://groupkash-fastapi.com/api/v1'
  domain_base_ws_url: 'ws://groupkash-fastapi.com/api/v1'
  docker_swarm_stack_name_main: 'groupkash-fastapi-com'
  docker_swarm_stack_name_staging: 'stag-groupkash-fastapi-com'
  secret_key: 'adc83ac73fe5dbd436a1cada6d63c21d4b2eb9b2931d09af71278427447e8d9f'
  first_superuser: 'admin@groupkash-fastapi.com'
  first_superuser_password: 'kdi#(kd345KOENG'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.groupkash-fastapi.com", "https://stag.groupkash-fastapi.com", "https://groupkash-fastapi.com"]'
  smtp_tls: 'True'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@groupkash-fastapi.com'
  smtp_emails_from_name: 'George Udosen'
  smtp_emails_to_email: 'info@groupkash-fastapi.com'
  mongodb_uri: 'mongodb'
  mongodb_database: 'groupkash-fastapi'
  traefik_constraint_tag: 'groupkash-fastapi.com'
  traefik_constraint_tag_staging: 'stag.groupkash-fastapi.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:kdi#(kd345KOENG'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/**/*.html, frontend/**/*.vue, frontend/.nuxt/*, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
